version: '3'
services:
    mydb:
        image: "postgres"
        env_file:
            - "database.env"
        volumes:
                - pgdata:/var/lib/postgresql/data
        ports:
                - "5433:5432"

volumes:
        pgdata:
